name: Build
jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-24.04-arm64]
        include:
          - platform: ubuntu-latest
            arch: amd64
          - platform: ubuntu-24.04-arm64
            arch: arm64
    steps:
      - run: echo "Build container image for arch: ${{ matrix.arch }}"
  manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "Create multi-arch manifest"
